'use client';
import {useEffect,useState} from 'react';
import type {User} from '@supabase/supabase-js';
import {Cloud,KeyRound,LogOut,ShieldCheck,Sparkles} from 'lucide-react';
import {getSupabase,supabaseConfigured} from '../lib/supabase';

const STORAGE_KEY='bonjour-bloom';
export function AccountGate({children}:{children:React.ReactNode}){
 const[user,setUser]=useState<User|null>(null),[ready,setReady]=useState(!supabaseConfigured),[mode,setMode]=useState<'signin'|'signup'>('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[sending,setSending]=useState(false),[synced,setSynced]=useState(false);
 useEffect(()=>{const supabase=getSupabase();if(!supabase)return;void supabase.auth.getUser().then(({data})=>{setUser(data.user);setReady(true)});const{data}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user||null);setReady(true)});return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!user)return;const supabase=getSupabase();if(!supabase)return;let active=true;async function hydrate(){const{data,error}=await supabase!.from('user_learning_state').select('state').eq('user_id',user!.id).maybeSingle();if(!active)return;if(!error&&data?.state){localStorage.setItem(STORAGE_KEY,JSON.stringify(data.state));window.dispatchEvent(new CustomEvent('bonjour-cloud-hydrate',{detail:data.state}))}else{const local=localStorage.getItem(STORAGE_KEY);if(local)await supabase!.from('user_learning_state').upsert({user_id:user!.id,state:JSON.parse(local),updated_at:new Date().toISOString()})}setSynced(true)}void hydrate();const save=async(event:Event)=>{const state=(event as CustomEvent).detail;if(state)await supabase.from('user_learning_state').upsert({user_id:user.id,state,updated_at:new Date().toISOString()})};window.addEventListener('bonjour-progress',save);return()=>{active=false;window.removeEventListener('bonjour-progress',save)}},[user]);
 async function submitAccount(e:React.FormEvent){e.preventDefault();const supabase=getSupabase();if(!supabase)return;setSending(true);setMessage('');if(mode==='signup'){const{data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}});setMessage(error?error.message:data.session?'Your account is ready. Welcome to Bonjour Bloom!':'Account created — check your email to confirm it, then sign in.')}else{const{error}=await supabase.auth.signInWithPassword({email,password});setMessage(error?error.message:'Welcome back!')}setSending(false)}
 if(!supabaseConfigured)return <><div className="demo-cloud-note"><Cloud/> Local demo · connect Supabase to enable email accounts</div>{children}</>;
 if(!ready)return <main className="account-loading"><Sparkles/><p>Opening your French garden…</p></main>;
 if(!user)return <main className="account-page"><section className="account-brand"><img src="/milo-icon.png" alt="Milo the fox"/><p className="eyebrow">BONJOUR BLOOM</p><h1>Your French journey,<br/>on every device.</h1><p>Create one family account, then return anytime to continue from where you stopped. Profiles and progress stay private and sync across devices.</p><div><span><ShieldCheck/> Private progress</span><span><Cloud/> Stay signed in</span></div></section><form className="account-card" onSubmit={submitAccount}><KeyRound/><div className="auth-tabs" role="tablist" aria-label="Account options"><button type="button" role="tab" aria-selected={mode==='signin'} onClick={()=>{setMode('signin');setMessage('')}}>Sign in</button><button type="button" role="tab" aria-selected={mode==='signup'} onClick={()=>{setMode('signup');setMessage('')}}>Sign up</button></div><h2>{mode==='signin'?'Welcome back':'Create your account'}</h2><p>{mode==='signin'?'Sign in and continue learning. You’ll stay signed in on this device.':'Use any email address to create your private learning account.'}</p><label>Email address<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input required minLength={6} type="password" autoComplete={mode==='signin'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></label><button className="primary" disabled={sending}>{sending?'Please wait…':mode==='signin'?'Sign in':'Create account'}</button>{message&&<p role="status" className="auth-message">{message}</p>}<small>For children, a parent or guardian should own and manage the account.</small></form></main>;
 return <><div className="account-bar"><span><Cloud/>{synced?'Progress synced':navigator.onLine?'Syncing…':'Saved offline'}</span><span>{user.email}<button onClick={()=>getSupabase()?.auth.signOut()}><LogOut/> Sign out</button></span></div>{children}</>
}
