'use client';
import {useEffect,useState} from 'react';
import type {User} from '@supabase/supabase-js';
import {Cloud,LogOut,Mail,ShieldCheck,Sparkles} from 'lucide-react';
import {getSupabase,supabaseConfigured} from '../lib/supabase';

const STORAGE_KEY='bonjour-bloom';
export function AccountGate({children}:{children:React.ReactNode}){
 const[user,setUser]=useState<User|null>(null),[ready,setReady]=useState(!supabaseConfigured),[email,setEmail]=useState(''),[message,setMessage]=useState(''),[sending,setSending]=useState(false),[synced,setSynced]=useState(false);
 useEffect(()=>{const supabase=getSupabase();if(!supabase)return;void supabase.auth.getUser().then(({data})=>{setUser(data.user);setReady(true)});const{data}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user||null);setReady(true)});return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!user)return;const supabase=getSupabase();if(!supabase)return;let active=true;async function hydrate(){const{data,error}=await supabase!.from('user_learning_state').select('state').eq('user_id',user!.id).maybeSingle();if(!active)return;if(!error&&data?.state){localStorage.setItem(STORAGE_KEY,JSON.stringify(data.state));window.dispatchEvent(new CustomEvent('bonjour-cloud-hydrate',{detail:data.state}))}else{const local=localStorage.getItem(STORAGE_KEY);if(local)await supabase!.from('user_learning_state').upsert({user_id:user!.id,state:JSON.parse(local),updated_at:new Date().toISOString()})}setSynced(true)}void hydrate();const save=async(event:Event)=>{const state=(event as CustomEvent).detail;if(state)await supabase.from('user_learning_state').upsert({user_id:user.id,state,updated_at:new Date().toISOString()})};window.addEventListener('bonjour-progress',save);return()=>{active=false;window.removeEventListener('bonjour-progress',save)}},[user]);
 async function sendLink(e:React.FormEvent){e.preventDefault();const supabase=getSupabase();if(!supabase)return;setSending(true);setMessage('');const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});setMessage(error?error.message:'Check your email for your secure sign-in link.');setSending(false)}
 if(!supabaseConfigured)return <><div className="demo-cloud-note"><Cloud/> Local demo · connect Supabase to enable email accounts</div>{children}</>;
 if(!ready)return <main className="account-loading"><Sparkles/><p>Opening your French garden…</p></main>;
 if(!user)return <main className="account-page"><section className="account-brand"><img src="/milo-icon.png" alt="Milo the fox"/><p className="eyebrow">BONJOUR BLOOM</p><h1>Your French journey,<br/>on every device.</h1><p>Sign in securely with any email. Your learner profiles and progress stay private to your account.</p><div><span><ShieldCheck/> Private progress</span><span><Cloud/> Sync across devices</span></div></section><form className="account-card" onSubmit={sendLink}><Mail/><h2>Sign in with email</h2><p>We’ll email you a secure link. No password to remember.</p><label>Email address<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><button className="primary" disabled={sending}>{sending?'Sending…':'Email me a sign-in link'}</button>{message&&<p role="status" className="auth-message">{message}</p>}<small>For children, a parent or guardian should own and manage the account.</small></form></main>;
 return <><div className="account-bar"><span><Cloud/>{synced?'Progress synced':navigator.onLine?'Syncing…':'Saved offline'}</span><span>{user.email}<button onClick={()=>getSupabase()?.auth.signOut()}><LogOut/> Sign out</button></span></div>{children}</>
}
