'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Mic,Pause,RotateCcw,ShieldCheck,Volume2,X} from 'lucide-react';
import {audioService} from '../lib/audio';

type State='intro'|'permission'|'recording'|'result'|'unsupported';
export function PronunciationPractice({expected,onDone}:{expected:string;onDone:()=>void}){const[state,setState]=useState<State>('intro'),[seconds,setSeconds]=useState(0),[message,setMessage]=useState(''),[audioUrl,setAudioUrl]=useState('');const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<number|null>(null),chunks=useRef<Blob[]>([]);
 const cleanup=()=>{if(timer.current)clearInterval(timer.current);timer.current=null;stream.current?.getTracks().forEach(track=>track.stop());stream.current=null};
 useEffect(()=>()=>{cleanup();if(audioUrl)URL.revokeObjectURL(audioUrl)},[audioUrl]);
 const hear=(slow=false)=>void audioService.play(expected,slow?'slow':'normal').catch(()=>setMessage('A French voice is not installed on this device. You can still read and practise aloud.'));
 async function start(){setState('permission');setMessage('');if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setState('unsupported');setMessage('Voice recording is not supported on this device.');return}try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const next=new MediaRecorder(stream.current);recorder.current=next;next.ondataavailable=event=>{if(event.data.size)chunks.current.push(event.data)};next.onstop=()=>{cleanup();const blob=new Blob(chunks.current,{type:next.mimeType||'audio/webm'});if(blob.size<400){setMessage('We couldn’t hear clearly. Try moving a little closer.');setAudioUrl('')}else{const url=URL.createObjectURL(blob);setAudioUrl(old=>{if(old)URL.revokeObjectURL(old);return url});setMessage(seconds<1?'That was very short — try saying the whole phrase.':'Recording ready. Listen back or try again.')}setState('result')};next.start(200);setSeconds(0);setState('recording');timer.current=window.setInterval(()=>setSeconds(value=>{if(value>=11){recorder.current?.stop();return 12}return value+1}),1000)}catch{cleanup();setState('unsupported');setMessage('Microphone permission is off. You can hear the model and practise aloud without recording.')}}
 function stop(){if(recorder.current?.state==='recording')recorder.current.stop()}
 function cancel(){if(recorder.current?.state==='recording'){recorder.current.onstop=null;recorder.current.stop()}cleanup();chunks.current=[];setSeconds(0);setState('intro')}
 return <main className="studio"><header><button onClick={onDone}><ArrowLeft/> Back to lesson</button><span><ShieldCheck/> Recordings stay on this device</span></header><section><p className="eyebrow">PRONUNCIATION PRACTICE</p><img src="/milo-icon.png" alt="Milo listening"/><h1>{expected}</h1><p>Hear the French model first. When you are ready, record up to 12 seconds.</p><div className="model-buttons"><button onClick={()=>hear()}><Volume2/> Hear it</button><button onClick={()=>hear(true)}><Volume2/> Hear it slowly</button></div>{state==='intro'&&<button className="record-cta" onClick={start}><Mic/> Record my voice</button>}{state==='permission'&&<p role="status">Waiting for microphone permission…</p>}{state==='recording'&&<><button className="mic-button recording" onClick={stop}><Pause/></button><b role="status">Recording… {seconds}s / 12s</b><button className="text-button" onClick={cancel}><X/> Cancel</button></>}{(state==='result'||state==='unsupported')&&<div className="speech-result"><h2>{message}</h2>{audioUrl&&<audio controls src={audioUrl} aria-label="Your voice recording"/>}<div>{audioUrl&&<button onClick={()=>setState('intro')}><RotateCcw/> Try again</button>}<button onClick={()=>hear()}><Volume2/> Model again</button><button className="primary" onClick={onDone}>Practise later</button></div></div>}</section></main>}
