import {describe,expect,it} from 'vitest';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {frenchFoundationPilot} from '../content/pilot/french-foundations';import {curriculumSchema,discoverLessons,variantFor} from './curriculum-foundation';
describe('Section 2 completion contracts',()=>{
 it('keeps the unverified pilot out of learner discovery',()=>{expect(frenchFoundationPilot.lessons.every(l=>l.status==='in_review')).toBe(true);expect(discoverLessons(frenchFoundationPilot,{learnerAgeBand:'8-11',proficiency:'pre_a1'})).toEqual([])});
 it('falls back only within the same safeguarding audience family',()=>{const lesson=structuredClone(frenchFoundationPilot.lessons[0]);lesson.variants=lesson.variants.filter(v=>v.audience!=='child_5_7');expect(variantFor(lesson,'child_5_7')?.audience).toBe('child_8_11');lesson.variants=lesson.variants.filter(v=>!v.audience.startsWith('child'));expect(variantFor(lesson,'child_5_7')).toBeUndefined()});
 it('rejects unknown skills and malformed scorable exercises',()=>{const bad=structuredClone(frenchFoundationPilot);bad.objectives[0].primarySkill='conversation' as never;expect(curriculumSchema.safeParse(bad).success).toBe(false);const malformed=structuredClone(frenchFoundationPilot);malformed.lessons[0].variants[0].exercises[0].options=[];expect(curriculumSchema.safeParse(malformed).success).toBe(false)});
 it('keeps French feature metadata outside universal tables',()=>{expect(frenchFoundationPilot.track.metadata).toHaveProperty('languageFeatures');const source=readFileSync(resolve('supabase/migrations/006_curriculum_foundation.sql'),'utf8');expect(source).not.toMatch(/\b(liaison|grammatical_gender|conjugation)\b/)});
 it('defines idempotent seeds and common query indexes',()=>{const seed=readFileSync(resolve('scripts/seed-curriculum.ts'),'utf8'),sql=readFileSync(resolve('supabase/migrations/006_curriculum_foundation.sql'),'utf8');expect(seed.match(/\.upsert\(/g)?.length).toBeGreaterThanOrEqual(7);expect(seed).toContain("onConflict:'module_id,slug'");expect(sql).toContain('curriculum_lessons_discovery_idx');expect(sql).toContain('lesson_variants_audience_idx')});
 it('includes responsive and accessible curriculum affordances',()=>{const css=readFileSync(resolve('app/curriculum/curriculum.css'),'utf8'),learner=readFileSync(resolve('app/curriculum/page.tsx'),'utf8'),admin=readFileSync(resolve('app/admin/curriculum/page.tsx'),'utf8');expect(css).toMatch(/@media\(max-width:(600|720)px\)/);expect(learner).toContain('role="status"');expect(admin).toContain('role="status"');expect(admin).toContain('<label>')});
});
