import {z} from 'zod';

export const cefrLevels=['pre_a1','a1','a2','b1','b2','c1','c2'] as const;
export const skillCodes=['listening','speaking','reading','writing','vocabulary','grammar','pronunciation','interaction'] as const;
export const lifecycleStates=['draft','in_review','reviewed','published','archived'] as const;
export const audienceBands=['child','teen','adult'] as const;

export const provenanceSchema=z.object({createdBy:z.string().min(1),sourceNotes:z.array(z.string()).default([]),license:z.string().min(1),reviewedBy:z.string().min(1).optional(),reviewedAt:z.string().datetime().optional()});
export const exerciseSchema=z.object({id:z.string().min(1),type:z.enum(['select','order','match','type','speak']),prompt:z.string().min(1),options:z.array(z.string()).optional(),answer:z.union([z.string(),z.array(z.string())]),points:z.number().int().positive().default(1)}).superRefine((value,ctx)=>{if(value.type==='select'&&(!value.options?.length||!value.options.includes(String(value.answer))))ctx.addIssue({code:'custom',message:'Select exercises require options containing the answer'});});
export const lessonVariantSchema=z.object({audience:z.enum(audienceBands),title:z.string().min(1),intro:z.string().min(1),sections:z.array(z.object({heading:z.string().min(1),body:z.string().min(1),items:z.array(z.object({target:z.string().min(1),translation:z.string().min(1),note:z.string().optional()})).default([])})).min(1),exercises:z.array(exerciseSchema).min(1)});
export const objectiveSchema=z.object({id:z.string().min(1),language:z.string().regex(/^[a-z]{2,3}$/),cefr:z.enum(cefrLevels),skills:z.array(z.enum(skillCodes)).min(1),statement:z.string().min(1),prerequisiteIds:z.array(z.string()).default([])});
export const lessonSchema=z.object({id:z.string().min(1),moduleId:z.string().min(1),language:z.string().regex(/^[a-z]{2,3}$/),cefr:z.enum(cefrLevels),status:z.enum(lifecycleStates),sequence:z.number().int().positive(),objectiveIds:z.array(z.string()).min(1),provenance:provenanceSchema,variants:z.array(lessonVariantSchema).length(3).superRefine((variants,ctx)=>{if(new Set(variants.map(v=>v.audience)).size!==3)ctx.addIssue({code:'custom',message:'One child, teen, and adult variant is required'});}),legacyLessonId:z.string().optional()});
export const moduleSchema=z.object({id:z.string().min(1),trackId:z.string().min(1),title:z.string().min(1),sequence:z.number().int().positive(),lessonIds:z.array(z.string()).min(1)});
export const curriculumSchema=z.object({schemaVersion:z.literal(2),track:z.object({id:z.string(),language:z.string().regex(/^[a-z]{2,3}$/),title:z.string(),active:z.boolean()}),objectives:z.array(objectiveSchema),modules:z.array(moduleSchema),lessons:z.array(lessonSchema)}).superRefine((value,ctx)=>{
 const objectiveIds=new Set(value.objectives.map(o=>o.id)),lessonIds=new Set(value.lessons.map(l=>l.id)),moduleIds=new Set(value.modules.map(m=>m.id));
 for(const lesson of value.lessons){if(!moduleIds.has(lesson.moduleId))ctx.addIssue({code:'custom',message:`Unknown module ${lesson.moduleId}`});for(const id of lesson.objectiveIds)if(!objectiveIds.has(id))ctx.addIssue({code:'custom',message:`Unknown objective ${id}`});}
 for(const curriculumModule of value.modules)for(const id of curriculumModule.lessonIds)if(!lessonIds.has(id))ctx.addIssue({code:'custom',message:`Unknown lesson ${id}`});
 const graph=new Map(value.objectives.map(o=>[o.id,o.prerequisiteIds]));const visiting=new Set<string>(),visited=new Set<string>();function visit(id:string){if(visiting.has(id)){ctx.addIssue({code:'custom',message:`Objective prerequisite cycle at ${id}`});return}if(visited.has(id))return;visiting.add(id);for(const dep of graph.get(id)||[]){if(!graph.has(dep))ctx.addIssue({code:'custom',message:`Unknown prerequisite ${dep}`});else visit(dep)}visiting.delete(id);visited.add(id)}for(const id of graph.keys())visit(id);
});

export type Curriculum=z.infer<typeof curriculumSchema>;export type CurriculumLesson=z.infer<typeof lessonSchema>;export type AudienceBand=typeof audienceBands[number];export type LifecycleState=typeof lifecycleStates[number];
export function audienceForAge(age:string):AudienceBand{return age==='18+'?'adult':age==='12-15'||age==='16-17'?'teen':'child'}
export function variantFor(lesson:CurriculumLesson,audience:AudienceBand){return lesson.variants.find(v=>v.audience===audience)??lesson.variants.find(v=>v.audience==='adult')??lesson.variants[0]}
export function scoreExercise(answer:string|string[],expected:string|string[],points:number){const a=Array.isArray(answer)?answer.join('|'):answer.trim().toLocaleLowerCase();const e=Array.isArray(expected)?expected.join('|'):expected.trim().toLocaleLowerCase();return a===e?points:0}
export function canTransition(from:LifecycleState,to:LifecycleState,hasReview:boolean){if(from==='archived')return false;if(to==='published')return from==='reviewed'&&hasReview;return ({draft:['in_review','archived'],in_review:['draft','reviewed','archived'],reviewed:['in_review','published','archived'],published:['archived']} as Record<LifecycleState,LifecycleState[]>)[from]?.includes(to)??false}
export function discoverLessons(curriculum:Curriculum,profile:{learnerAgeBand?:string;proficiency?:string},completedIds:string[]=[]){const level=profile.proficiency||'pre_a1',doneLessons=new Set(completedIds),done=new Set(completedIds);for(const lesson of curriculum.lessons)if(doneLessons.has(lesson.id)||Boolean(lesson.legacyLessonId&&doneLessons.has(lesson.legacyLessonId)))for(const id of lesson.objectiveIds)done.add(id);return curriculum.lessons.filter(l=>l.status==='published'&&l.cefr===level&&l.objectiveIds.every(id=>{const objective=curriculum.objectives.find(o=>o.id===id);return objective?.prerequisiteIds.every(dep=>done.has(dep))!==false})).sort((a,b)=>a.sequence-b.sequence).map(lesson=>({lesson,variant:variantFor(lesson,audienceForAge(profile.learnerAgeBand||'18+'))}));}
