import { z } from 'zod';
export const vocabularySchema = z.object({id:z.string(),french:z.string().min(1),english:z.string().min(1),article:z.string(),gender:z.enum(['m','f','n']),partOfSpeech:z.string(),hint:z.string(),level:z.string(),topic:z.string(),emoji:z.string(),example:z.string(),translation:z.string()});
export type VocabularyEntry=z.infer<typeof vocabularySchema>;
const rows:Array<[string,string,string,'m'|'f'|'n',string,string,string]>=[
['bonjour','hello','','n','greetings','👋','Bonjour, Léo !'],['salut','hi','','n','greetings','😊','Salut, ça va ?'],['au revoir','goodbye','','n','greetings','🌤️','Au revoir, maman !'],['merci','thank you','','n','greetings','💛','Merci beaucoup !'],['oui','yes','','n','phrases','👍','Oui, s’il te plaît.'],['non','no','','n','phrases','🙅','Non, merci.'],['chat','cat','le','m','animals','🐱','Le chat est noir.'],['chien','dog','le','m','animals','🐶','Le chien joue.'],['lapin','rabbit','le','m','animals','🐰','Le lapin est blanc.'],['oiseau','bird','l’','m','animals','🐦','L’oiseau chante.'],['poisson','fish','le','m','animals','🐟','Le poisson nage.'],['rouge','red','','n','colors','🔴','La pomme est rouge.'],['bleu','blue','','n','colors','🔵','Le ciel est bleu.'],['jaune','yellow','','n','colors','🟡','Le soleil est jaune.'],['vert','green','','n','colors','🟢','La feuille est verte.'],['un','one','','n','numbers','1️⃣','Un chat.'],['deux','two','','n','numbers','2️⃣','Deux chiens.'],['trois','three','','n','numbers','3️⃣','Trois pommes.'],['quatre','four','','n','numbers','4️⃣','Quatre livres.'],['cinq','five','','n','numbers','5️⃣','Cinq oiseaux.'],['maman','mum','la','f','family','👩','Ma maman sourit.'],['papa','dad','le','m','family','👨','Mon papa cuisine.'],['frère','brother','le','m','family','👦','Mon frère joue.'],['sœur','sister','la','f','family','👧','Ma sœur lit.'],['pomme','apple','la','f','food','🍎','Je mange une pomme.'],['pain','bread','le','m','food','🥖','Le pain est bon.'],['eau','water','l’','f','food','💧','Je bois de l’eau.'],['lait','milk','le','m','food','🥛','Le lait est froid.'],['école','school','l’','f','school','🏫','Je vais à l’école.'],['livre','book','le','m','school','📘','Je lis un livre.'],['crayon','pencil','le','m','school','✏️','Voici un crayon.'],['maison','house','la','f','home','🏠','Ma maison est ici.'],['porte','door','la','f','home','🚪','Ouvre la porte.'],['main','hand','la','f','body','✋','Lève la main.'],['tête','head','la','f','body','🙂','Touche ta tête.'],['soleil','sun','le','m','weather','☀️','Il y a du soleil.'],['pluie','rain','la','f','weather','🌧️','Il y a de la pluie.'],['bus','bus','le','m','transport','🚌','Je prends le bus.'],['vélo','bike','le','m','transport','🚲','J’aime mon vélo.'],['heureux','happy','','n','feelings','😄','Je suis heureux.'],['triste','sad','','n','feelings','😢','Je suis triste.'],['manger','to eat','','n','routines','🍽️','J’aime manger.'],['dormir','to sleep','','n','routines','😴','Je vais dormir.'],['jouer','to play','','n','routines','🪁','Je veux jouer.']];
export const vocabulary:VocabularyEntry[]=rows.map(([french,english,article,gender,topic,emoji,example],index)=>vocabularySchema.parse({id:`v${index+1}`,french,english,article,gender,partOfSpeech:article?'noun':'word',hint:french,level:'Pre-A1',topic,emoji,example,translation:english}));
export const phrases=['Comment ça va ?','Je m’appelle…','S’il te plaît.','J’aime le français.','Je voudrais de l’eau.','Où est le chat ?','Je ne comprends pas.','Peux-tu répéter ?','À bientôt !','Bonne nuit !'];
export const lessons=[
{id:'hello',title:'Hello, France!',subtitle:'Greetings and first sounds',minutes:6,color:'#ef6a5b',exercises:[{kind:'listen',prompt:'Listen, then tap the greeting',answer:'bonjour',options:['bonjour','merci','au revoir'],emoji:'👋'},{kind:'picture',prompt:'Which picture means “cat”?',answer:'chat',options:['chat','chien','oiseau'],emoji:'🐱'},{kind:'order',prompt:'Build: “My name is Milo”',answer:'Je m’appelle Milo',options:['Milo','m’appelle','Je'],emoji:'🧩'},{kind:'speak',prompt:'Say it with Milo',answer:'Bonjour !',options:[],emoji:'🎙️'}]},
{id:'colors',title:'A rainbow picnic',subtitle:'Colours and food',minutes:7,color:'#47a887',exercises:[{kind:'picture',prompt:'Tap the red apple',answer:'rouge',options:['rouge','bleu','vert'],emoji:'🍎'},{kind:'listen',prompt:'Listen and choose',answer:'pomme',options:['pain','pomme','lait'],emoji:'🔊'},{kind:'missing',prompt:'La pomme est ___.',answer:'rouge',options:['rouge','deux','bonjour'],emoji:'✏️'}]},
{id:'animals',title:'Animals at home',subtitle:'Listen, match and recall',minutes:8,color:'#6577c8',exercises:[{kind:'listen',prompt:'What did you hear?',answer:'chien',options:['chat','chien','lapin'],emoji:'🐶'},{kind:'picture',prompt:'Find le lapin',answer:'lapin',options:['poisson','oiseau','lapin'],emoji:'🐰'},{kind:'order',prompt:'Build: “The cat plays”',answer:'Le chat joue',options:['joue','Le','chat'],emoji:'🧩'}]},
{id:'review',title:'Garden review',subtitle:'A gentle mastery check',minutes:5,color:'#d89532',exercises:[{kind:'picture',prompt:'Which word means “blue”?',answer:'bleu',options:['bleu','rouge','jaune'],emoji:'🔵'},{kind:'missing',prompt:'___ revoir !',answer:'Au',options:['Au','Le','Je'],emoji:'🌤️'}]}];
export type Exercise=typeof lessons[number]['exercises'][number];
export const curriculumSchema=z.object({vocabulary:z.array(vocabularySchema).min(40),phrases:z.array(z.string()).min(10),lessons:z.array(z.object({id:z.string(),title:z.string(),subtitle:z.string(),minutes:z.number(),color:z.string(),exercises:z.array(z.object({kind:z.string(),prompt:z.string(),answer:z.string(),options:z.array(z.string()),emoji:z.string()})).min(2)})).min(4)});
export const curriculum=curriculumSchema.parse({vocabulary,phrases,lessons});
