import {z} from 'zod';
import {starterCourse} from './starter-course';

export const vocabularySchema=z.object({id:z.string(),french:z.string().min(1),english:z.string().min(1),article:z.string(),gender:z.enum(['m','f','n']),partOfSpeech:z.string(),hint:z.string(),level:z.string(),topic:z.string(),emoji:z.string(),example:z.string(),translation:z.string(),audio:z.string(),slowAudio:z.string()});
export type VocabularyEntry=z.infer<typeof vocabularySchema>;
export const vocabulary:VocabularyEntry[]=starterCourse.vocabulary.map(v=>vocabularySchema.parse({id:v.id,french:v.french,english:v.english,article:v.article,gender:v.gender==='masculine'?'m':v.gender==='feminine'?'f':'n',partOfSpeech:v.partOfSpeech,hint:v.pronunciation,level:v.cefr,topic:v.topic,emoji:v.image,example:v.example,translation:v.exampleTranslation,audio:v.audio,slowAudio:v.slowAudio}));
const kindMap={'audio-picture':'picture','audio-word':'listen','fr-en':'picture','en-fr':'picture','multiple-choice':'picture','missing-word':'missing','sentence-order':'order','listening':'listen','dictation':'missing','pronunciation':'speak','dialogue-response':'picture','review':'picture'} as const;
export const lessons=starterCourse.lessons.map(lesson=>({id:lesson.id,title:lesson.title,subtitle:lesson.subtitle,outcome:lesson.outcome,minutes:lesson.minutes,color:lesson.color,sections:lesson.sections,dialogue:lesson.dialogue,exercises:lesson.exercises.map(ex=>({id:ex.id,kind:kindMap[ex.type],prompt:ex.prompt,answer:ex.type==='sentence-order'?ex.answer:(ex.options.find(o=>o.id===ex.answer)?.label||ex.answer),options:ex.options.map(o=>o.label),emoji:ex.options.find(o=>o.id===ex.answer)?.image||starterCourse.vocabulary.find(v=>v.id===ex.answer)?.image||'✦',audioText:ex.audioText,ageModes:ex.ageModes,explanation:ex.explanation}))}));
export type Exercise=typeof lessons[number]['exercises'][number];
export const phrases=starterCourse.lessons.flatMap(l=>l.dialogue.map(d=>d.french));
export const curriculumSchema=z.object({vocabulary:z.array(vocabularySchema).min(35),phrases:z.array(z.string()).min(5),lessons:z.array(z.object({id:z.string(),title:z.string(),subtitle:z.string(),minutes:z.number(),color:z.string(),exercises:z.array(z.object({id:z.string(),kind:z.string(),prompt:z.string(),answer:z.string(),options:z.array(z.string()),emoji:z.string(),audioText:z.string().optional(),ageModes:z.array(z.string()),explanation:z.string().optional()})).min(6)})).length(5)});
export const curriculum=curriculumSchema.parse({vocabulary,phrases,lessons});
