import {z} from 'zod';

export const cefrLevels=['pre_a1','a1','a2','b1','b2','c1','c2'] as const;
export const skillCodes=['reading','writing','listening','speaking','spoken_interaction','written_interaction','vocabulary','grammar','pronunciation','mediation'] as const;
export const lifecycleStates=['draft','in_review','reviewed','published','archived'] as const;
export const audienceBands=['child_5_7','child_8_11','teen_12_15','teen_16_17','adult'] as const;

export const provenanceSchema=z.object({createdBy:z.string().min(1),sourceName:z.string().min(1),sourceUrl:z.string().url().optional(),externalId:z.string().optional(),license:z.string().min(1),attribution:z.string().min(1),sourceVersion:z.string().optional(),sourceDate:z.string().optional(),importedAt:z.string().datetime().optional(),sourceNotes:z.array(z.string()).default([]),reviewedBy:z.string().min(1).optional(),reviewedAt:z.string().datetime().optional(),reviewNotes:z.string().optional()});
export const exerciseSchema=z.object({id:z.string().min(1),type:z.enum(['instruction','prompt_card','listen_select','match','multiple_choice','true_false','reorder','fill_gap','short_answer','listen_repeat','dialogue','reflection']),prompt:z.string().min(1),options:z.array(z.string()).optional(),answer:z.union([z.string(),z.array(z.string())]).optional(),acceptedAnswers:z.array(z.string()).optional(),feedback:z.string().optional(),skill:z.enum(skillCodes),difficulty:z.number().int().min(1).max(5),hint:z.string().optional(),mediaRef:z.string().url().optional(),scoring:z.enum(['exact','case_insensitive','ordered']).optional(),points:z.number().int().positive().default(1)}).superRefine((value,ctx)=>{if(['listen_select','multiple_choice','true_false'].includes(value.type)&&(!value.options?.length||!value.options.includes(String(value.answer||''))))ctx.addIssue({code:'custom',message:'Select exercises require options containing the answer'});});
export const lessonVariantSchema=z.object({audience:z.enum(audienceBands),title:z.string().min(1),intro:z.string().min(1),sections:z.array(z.object({heading:z.string().min(1),body:z.string().min(1),items:z.array(z.object({target:z.string().min(1),translation:z.string().min(1),note:z.string().optional()})).default([])})).min(1),exercises:z.array(exerciseSchema).min(1)});
export const objectiveSchema=z.object({id:z.string().min(1),language:z.string().regex(/^[a-z]{2,3}(-[A-Z]{2})?$/),cefr:z.enum(cefrLevels),primarySkill:z.enum(skillCodes),secondarySkills:z.array(z.enum(skillCodes)).default([]),topicTags:z.array(z.string()).min(1),statement:z.string().min(1),authoringNotes:z.string().min(1),masteryEvidence:z.enum(['recognition','production','interaction','completion']),status:z.enum(lifecycleStates),cefrRationale:z.string().min(1),prerequisiteIds:z.array(z.string()).default([])});
export const lessonSchema=z.object({id:z.string().min(1),moduleId:z.string().min(1),language:z.string().regex(/^[a-z]{2,3}(-[A-Z]{2})?$/),locale:z.string().min(2),cefr:z.enum(cefrLevels),primarySkill:z.enum(skillCodes),secondarySkills:z.array(z.enum(skillCodes)).default([]),topicTags:z.array(z.string()).min(1),estimatedMinutes:z.number().int().positive(),active:z.boolean(),deprecated:z.boolean().default(false),status:z.enum(lifecycleStates),sequence:z.number().int().positive(),objectiveIds:z.array(z.string()).min(1),provenance:provenanceSchema,variants:z.array(lessonVariantSchema).min(1).superRefine((variants,ctx)=>{if(new Set(variants.map(v=>v.audience)).size!==variants.length)ctx.addIssue({code:'custom',message:'Audience variants must be unique'});}),legacyLessonId:z.string().optional()});
export const moduleSchema=z.object({id:z.string().min(1),trackId:z.string().min(1),title:z.string().min(1),sequence:z.number().int().positive(),lessonIds:z.array(z.string()).min(1)});
export const curriculumSchema=z.object({schemaVersion:z.literal(2),track:z.object({id:z.string(),language:z.string().regex(/^[a-z]{2,3}(-[A-Z]{2})?$/),interfaceLanguage:z.string().min(2),locale:z.string().min(2),writingDirection:z.enum(['ltr','rtl']),script:z.string().min(4).optional(),title:z.string(),active:z.boolean(),metadata:z.record(z.string(),z.unknown()).default({})}),objectives:z.array(objectiveSchema),modules:z.array(moduleSchema),lessons:z.array(lessonSchema)}).superRefine((value,ctx)=>{
 const objectiveIds=new Set(value.objectives.map(o=>o.id)),lessonIds=new Set(value.lessons.map(l=>l.id)),moduleIds=new Set(value.modules.map(m=>m.id));
 for(const lesson of value.lessons){if(!moduleIds.has(lesson.moduleId))ctx.addIssue({code:'custom',message:`Unknown module ${lesson.moduleId}`});for(const id of lesson.objectiveIds)if(!objectiveIds.has(id))ctx.addIssue({code:'custom',message:`Unknown objective ${id}`});}
 for(const curriculumModule of value.modules)for(const id of curriculumModule.lessonIds)if(!lessonIds.has(id))ctx.addIssue({code:'custom',message:`Unknown lesson ${id}`});
 const graph=new Map(value.objectives.map(o=>[o.id,o.prerequisiteIds]));const visiting=new Set<string>(),visited=new Set<string>();function visit(id:string){if(visiting.has(id)){ctx.addIssue({code:'custom',message:`Objective prerequisite cycle at ${id}`});return}if(visited.has(id))return;visiting.add(id);for(const dep of graph.get(id)||[]){if(!graph.has(dep))ctx.addIssue({code:'custom',message:`Unknown prerequisite ${dep}`});else visit(dep)}visiting.delete(id);visited.add(id)}for(const id of graph.keys())visit(id);
});

export type Curriculum=z.infer<typeof curriculumSchema>;export type CurriculumLesson=z.infer<typeof lessonSchema>;export type AudienceBand=typeof audienceBands[number];export type LifecycleState=typeof lifecycleStates[number];
export function audienceForAge(age:string):AudienceBand{return age==='5-7'?'child_5_7':age==='8-11'?'child_8_11':age==='12-15'?'teen_12_15':age==='16-17'?'teen_16_17':'adult'}
export function variantFor(lesson:CurriculumLesson,audience:AudienceBand){const fallbacks:Record<AudienceBand,AudienceBand[]>={child_5_7:['child_5_7','child_8_11'],child_8_11:['child_8_11','child_5_7'],teen_12_15:['teen_12_15','teen_16_17'],teen_16_17:['teen_16_17','teen_12_15'],adult:['adult']};for(const band of fallbacks[audience]){const match=lesson.variants.find(v=>v.audience===band);if(match)return match}return undefined}
export function scoreExercise(answer:string|string[],expected:string|string[],points:number){const a=Array.isArray(answer)?answer.join('|'):answer.trim().toLocaleLowerCase();const e=Array.isArray(expected)?expected.join('|'):expected.trim().toLocaleLowerCase();return a===e?points:0}
export function canTransition(from:LifecycleState,to:LifecycleState,hasReview:boolean){if(from==='archived')return false;if(to==='published')return from==='reviewed'&&hasReview;return ({draft:['in_review','archived'],in_review:['draft','reviewed','archived'],reviewed:['in_review','published','archived'],published:['archived']} as Record<LifecycleState,LifecycleState[]>)[from]?.includes(to)??false}
export function discoverLessons(curriculum:Curriculum,profile:{learnerAgeBand?:string;proficiency?:string},completedIds:string[]=[]){const level=profile.proficiency||'pre_a1',doneLessons=new Set(completedIds),done=new Set(completedIds);for(const lesson of curriculum.lessons)if(doneLessons.has(lesson.id)||Boolean(lesson.legacyLessonId&&doneLessons.has(lesson.legacyLessonId)))for(const id of lesson.objectiveIds)done.add(id);return curriculum.lessons.filter(l=>l.status==='published'&&l.cefr===level&&l.objectiveIds.every(id=>{const objective=curriculum.objectives.find(o=>o.id===id);return objective?.prerequisiteIds.every(dep=>done.has(dep))!==false})).sort((a,b)=>a.sequence-b.sequence).flatMap(lesson=>{const variant=variantFor(lesson,audienceForAge(profile.learnerAgeBand||'18+'));return variant?[{lesson,variant}]:[]});}
