import {describe,expect,it} from 'vitest';import {frenchFoundationPilot} from '../content/pilot/french-foundations';import {audienceForAge,canTransition,curriculumSchema,discoverLessons,scoreExercise,variantFor} from './curriculum-foundation';
describe('curriculum foundation',()=>{
 it('validates the two-module six-lesson pilot',()=>{expect(curriculumSchema.safeParse(frenchFoundationPilot).success).toBe(true);expect(frenchFoundationPilot.modules).toHaveLength(2);expect(frenchFoundationPilot.lessons).toHaveLength(6);expect(frenchFoundationPilot.lessons.reduce((n,l)=>n+l.variants[0].sections[0].items.length,0)).toBe(48)});
 it('has exactly one complete audience set per lesson',()=>{for(const lesson of frenchFoundationPilot.lessons)expect(lesson.variants.map(v=>v.audience).sort()).toEqual(['adult','child_5_7','child_8_11','teen_12_15','teen_16_17'])});
 it('selects the profile-aware variant',()=>{const lesson=frenchFoundationPilot.lessons[0];expect(audienceForAge('5-7')).toBe('child_5_7');expect(audienceForAge('12-15')).toBe('teen_12_15');expect(audienceForAge('18+')).toBe('adult');expect(variantFor(lesson,'teen_12_15')?.audience).toBe('teen_12_15')});
 it('never exposes review-stage content',()=>{const discovered=discoverLessons(frenchFoundationPilot,{learnerAgeBand:'18+',proficiency:'pre_a1'},frenchFoundationPilot.objectives.map(o=>o.id));expect(discovered.every(x=>x.lesson.status==='published')).toBe(true);expect(discovered.some(x=>x.lesson.id.includes('wellbeing'))).toBe(false)});
 it('enforces governance transitions',()=>{expect(canTransition('draft','published',true)).toBe(false);expect(canTransition('reviewed','published',false)).toBe(false);expect(canTransition('reviewed','published',true)).toBe(true);expect(canTransition('published','draft',true)).toBe(false)});
 it('scores structured answers deterministically',()=>{expect(scoreExercise(' Bonjour ','bonjour',2)).toBe(2);expect(scoreExercise(['un','deux'],['un','deux'],3)).toBe(3);expect(scoreExercise('salut','bonjour',1)).toBe(0)});
 it('rejects prerequisite cycles',()=>{const copy=structuredClone(frenchFoundationPilot);copy.objectives[0].prerequisiteIds=[copy.objectives.at(-1)!.id];expect(curriculumSchema.safeParse(copy).success).toBe(false)});
});
