import type {TeacherVoice} from './audio';
export type AgeBand='early'|'junior'|'explorer'|'adult';
export type LearnerAgeBand='5-7'|'8-11'|'12-15'|'16-17'|'18+';
export type ProfileType='child'|'teen'|'adult';
export type CefrLevel='pre_a1'|'a1'|'a2'|'b1'|'b2'|'c1'|'c2';
export type LearningGoal='general'|'school'|'travel'|'conversation'|'work_business'|'exam_prep';
export type AccountMode='individual'|'family';
export type ProfilePermissions={microphone:boolean;aiFeatures:boolean;externalVideos:boolean;liveCoaching:boolean;reminders:boolean};
export type ReviewGrade='again'|'hard'|'good'|'easy';
export type MasteryState={itemId:string;stability:number;difficulty:number;dueAt:string;lastReviewedAt:string;repetitions:number;lapses:number};
export type ExerciseAttemptRecord={exerciseId:string;lessonId:string;correct:boolean;hintsUsed:number;at:string};
export type Profile={id:string;name:string;ageBand:AgeBand;avatar:string;dailyGoal:number;completed:string[];xp:number;minutes:number;reviews:number;learnerAgeBand?:LearnerAgeBand;profileType?:ProfileType;targetLanguage?:string;interfaceLanguage?:string;proficiency?:CefrLevel;levelConfirmed?:boolean;learningGoal?:LearningGoal;dailyTargetMinutes?:5|10|15|20|30;archived?:boolean;permissions?:ProfilePermissions;teacherVoice?:TeacherVoice;mastery?:Record<string,MasteryState>;speakingAttempts?:number;largeText?:boolean;currentLesson?:string;currentActivity?:number;attempts?:ExerciseAttemptRecord[];correctAnswers?:number;totalAnswers?:number;lastActivityDate?:string;streakDays?:number;achievements?:string[];microphoneEnabled?:boolean};
export type OnboardingDraft={step:number;accountMode:AccountMode;profile?:Partial<Profile>};
export type AppData={guardianReady:boolean;parentPin:string;activeProfileId:string;profiles:Profile[];downloaded:boolean;sound:boolean;streak:boolean;accountMode?:AccountMode;onboarding?:OnboardingDraft};
export const safePermissions:ProfilePermissions={microphone:false,aiFeatures:false,externalVideos:false,liveCoaching:false,reminders:false};
export const adultPermissions:ProfilePermissions={microphone:true,aiFeatures:true,externalVideos:true,liveCoaching:false,reminders:false};
export const initialData:AppData={guardianReady:false,parentPin:'2468',activeProfileId:'',profiles:[],downloaded:false,sound:true,streak:true};
export const profileTypeForAge:Record<LearnerAgeBand,ProfileType>={'5-7':'child','8-11':'child','12-15':'teen','16-17':'teen','18+':'adult'};
export const cefrLabels:Record<CefrLevel,string>={pre_a1:'New Learner',a1:'Beginner',a2:'Elementary',b1:'Intermediate',b2:'Upper Intermediate',c1:'Advanced',c2:'Mastery'};
export const goalLabels:Record<LearningGoal,string>={general:'General learning',school:'School',travel:'Travel',conversation:'Conversation',work_business:'Work / business',exam_prep:'Exam preparation'};
export function presentationAge(age:LearnerAgeBand):AgeBand{return age==='5-7'?'early':age==='8-11'?'junior':age==='18+'?'adult':'explorer'}
export function hydrateProfile(p:Profile):Profile{const learnerAgeBand=p.learnerAgeBand||(p.ageBand==='early'?'5-7':p.ageBand==='junior'||p.ageBand==='explorer'?'8-11':'18+'),profileType=profileTypeForAge[learnerAgeBand];return{...p,learnerAgeBand,profileType,targetLanguage:p.targetLanguage||'fr',interfaceLanguage:p.interfaceLanguage||'en',proficiency:p.proficiency||'pre_a1',levelConfirmed:p.levelConfirmed??false,learningGoal:p.learningGoal||'general',dailyTargetMinutes:p.dailyTargetMinutes||(p.dailyGoal===1?5:p.dailyGoal===2?10:15),archived:p.archived??false,permissions:{...(profileType==='adult'?adultPermissions:safePermissions),...(p.permissions||{})}}}
export function normalizeAppData(value:unknown):AppData{const raw=(value&&typeof value==='object'?value:{}) as Partial<AppData>;const profiles=(raw.profiles||[]).map(hydrateProfile),active=profiles.find(p=>p.id===raw.activeProfileId&&!p.archived)||profiles.find(p=>!p.archived);return{...initialData,...raw,accountMode:raw.accountMode||(profiles.length>1?'family':profiles.length?'individual':undefined),guardianReady:raw.guardianReady??profiles.length>0,profiles,activeProfileId:active?.id||''}}
export function createLearnerProfile(input:{name:string;learnerAgeBand:LearnerAgeBand;avatar:string;proficiency:CefrLevel;levelConfirmed:boolean;learningGoal:LearningGoal;dailyTargetMinutes:5|10|15|20|30}):Profile{const profileType=profileTypeForAge[input.learnerAgeBand];return{...input,id:crypto.randomUUID(),ageBand:presentationAge(input.learnerAgeBand),profileType,targetLanguage:'fr',interfaceLanguage:'en',archived:false,permissions:profileType==='adult'?{...adultPermissions}:{...safePermissions},dailyGoal:Math.max(1,Math.ceil(input.dailyTargetMinutes/10)),completed:[],xp:0,minutes:0,reviews:0,mastery:{},speakingAttempts:0}}
export function archiveProfile(data:AppData,id:string){if(data.profiles.filter(p=>!p.archived).length<=1)return data;const profiles=data.profiles.map(p=>p.id===id?{...p,archived:true}:p),next=profiles.find(p=>!p.archived);return{...data,profiles,activeProfileId:data.activeProfileId===id?(next?.id||''):data.activeProfileId}}
export function goalPercent(profile:Profile){return profile.dailyTargetMinutes?Math.min(100,Math.round((profile.minutes/profile.dailyTargetMinutes)*100)):Math.min(100,Math.round((profile.completed.length/profile.dailyGoal)*100))}
export function reviewDue(completed:number,lastReviewedDaysAgo=2){return completed>0&&lastReviewedDaysAgo>=Math.min(7,completed*2)}
export function pronunciationLabel(confidence:number|null){if(confidence===null||confidence<.35)return'We couldn’t hear clearly';if(confidence>=.82)return'Great';if(confidence>=.58)return'Almost';return'Let’s practise'}
export function scheduleReview(previous:MasteryState|undefined,itemId:string,grade:ReviewGrade,now=new Date()):MasteryState{const old=previous||{itemId,stability:0,difficulty:5,dueAt:now.toISOString(),lastReviewedAt:now.toISOString(),repetitions:0,lapses:0};const factor={again:.2,hard:1.2,good:2.2,easy:3.8}[grade],stability=grade==='again'?.5:Math.max(1,(old.stability||1)*factor),difficulty=Math.min(10,Math.max(1,old.difficulty+(grade==='again'?1:grade==='easy'?-.6:0)));return{...old,stability,difficulty,lastReviewedAt:now.toISOString(),dueAt:new Date(now.getTime()+stability*86400000).toISOString(),repetitions:old.repetitions+1,lapses:old.lapses+(grade==='again'?1:0)}}
export function dueItems(mastery:Record<string,MasteryState>|undefined,now=new Date()){return Object.values(mastery||{}).filter(x=>new Date(x.dueAt)<=now).sort((a,b)=>a.dueAt.localeCompare(b.dueAt))}
export function completeLesson(profile:Profile,lessonId:string,minutes:number,now=new Date()):Profile{if(profile.completed.includes(lessonId))return{...profile,currentLesson:undefined,currentActivity:0,lastActivityDate:now.toISOString()};const completed=[...profile.completed,lessonId],achievements=new Set(profile.achievements||[]);if(completed.length>=1)achievements.add('first-lesson');if(Object.keys(profile.mastery||{}).length>=5)achievements.add('five-words');if((profile.speakingAttempts||0)>0)achievements.add('speaking-star');if((profile.streakDays||0)>=3)achievements.add('three-day-practice');return{...profile,completed,xp:profile.xp+40,minutes:profile.minutes+minutes,currentLesson:undefined,currentActivity:0,lastActivityDate:now.toISOString(),achievements:[...achievements]}}
export function accuracy(profile:Profile){return profile.totalAnswers?Math.round(((profile.correctAnswers||0)/profile.totalAnswers)*100):0}
