export type PronunciationFailure='permission-denied'|'unsupported'|'provider-failed'|'too-quiet'|'too-noisy'|'no-speech';
export type SoundResult={symbol:string;accuracy:number;tip?:string};
export type WordResult={expected:string;recognized?:string;accuracy?:number;sounds?:SoundResult[];error?:'omission'|'insertion'|'substitution'};
export type PronunciationResult={expectedText:string;recognizedText?:string;confidence?:number;words?:WordResult[];insertions:string[];omissions:string[];substitutions:string[];fluency?:number;completeness?:number;reliability:'high'|'medium'|'low'|'unavailable';provider:string;providerVersion:string;failureReason?:PronunciationFailure};
export interface PronunciationProvider{readonly id:string;assess(audio:Blob,expectedText:string):Promise<PronunciationResult>}
export class LocalDemoPronunciationProvider implements PronunciationProvider{readonly id='local-demo';async assess(audio:Blob,expectedText:string):Promise<PronunciationResult>{return{expectedText,insertions:[],omissions:[],substitutions:[],reliability:'unavailable',provider:this.id,providerVersion:'1',failureReason:audio.size<300?'too-quiet':'provider-failed'}}}
export class ProductionPronunciationProvider implements PronunciationProvider{readonly id='production';constructor(private endpoint='/api/pronunciation'){}async assess(audio:Blob,expectedText:string){const form=new FormData();form.append('audio',audio);form.append('expectedText',expectedText);const response=await fetch(this.endpoint,{method:'POST',body:form});if(!response.ok)throw new Error('pronunciation-provider-failed');return await response.json() as PronunciationResult}}
export class MockPronunciationProvider implements PronunciationProvider{readonly id='mock';constructor(private result:PronunciationResult){}async assess(_audio:Blob,_expectedText:string){return this.result}}
export function feedbackLabel(result:PronunciationResult){if(result.reliability==='unavailable'||result.failureReason||result.confidence===undefined||result.confidence<.35)return 'We could not hear clearly';if(result.confidence>=.9&&result.completeness!==undefined&&result.completeness>=.9)return 'Excellent';if(result.confidence>=.72)return 'Good — retry this sound';return 'Almost'}
