import {courseSchema,type Course} from './course-model';

const vocabRows=[
 ['bonjour','Bonjour','Hello','👋'],['salut','Salut','Hi','😊'],['bonsoir','Bonsoir','Good evening','🌙'],['au-revoir','Au revoir','Goodbye','👋'],['merci','Merci','Thank you','💛'],['svp','S’il vous plaît','Please','🙏'],['oui','Oui','Yes','👍'],['non','Non','No','🙅'],
 ['je-mappelle','Je m’appelle…','My name is…','🙋'],['comment-tu','Comment tu t’appelles ?','What is your name?','❓'],['enchante','Enchanté / Enchantée','Nice to meet you','🤝'],['je-suis','Je suis…','I am…','🙂'],
 ['un','Un','One','1️⃣'],['deux','Deux','Two','2️⃣'],['trois','Trois','Three','3️⃣'],['quatre','Quatre','Four','4️⃣'],['cinq','Cinq','Five','5️⃣'],['six','Six','Six','6️⃣'],['sept','Sept','Seven','7️⃣'],['huit','Huit','Eight','8️⃣'],['neuf','Neuf','Nine','9️⃣'],['dix','Dix','Ten','🔟'],['age','Quel âge as-tu ?','How old are you?','🎂'],
 ['rouge','Rouge','Red','🔴'],['bleu','Bleu','Blue','🔵'],['vert','Vert','Green','🟢'],['jaune','Jaune','Yellow','🟡'],['orange','Orange','Orange','🟠'],['rose','Rose','Pink','🌸'],['noir','Noir','Black','⚫'],['blanc','Blanc','White','⚪'],['marron','Marron','Brown','🟤'],['violet','Violet','Purple','🟣'],
 ['famille','La famille','Family','👨‍👩‍👧‍👦'],['mere','La mère','Mother','👩'],['pere','Le père','Father','👨'],['soeur','La sœur','Sister','👧'],['frere','Le frère','Brother','👦'],['parents','Les parents','Parents','🧑‍🤝‍🧑'],['qui','Qui est-ce ?','Who is it?','❓']
] as const;
const vocabulary=vocabRows.map(([id,french,english,image],order)=>({id,french,english,article:/^L[ae]s? |^Le |^La /.test(french)?french.split(' ')[0]:'',gender:french.startsWith('La ')?'feminine' as const:french.startsWith('Le ')?'masculine' as const:'not-applicable' as const,partOfSpeech:'beginner phrase',pronunciation:french,audio:`tts:${id}`,slowAudio:`tts:${id}:slow`,image,example:french,exampleTranslation:english,cefr:'Pre-A1' as const,topic:order<8?'greetings':order<12?'introductions':order<23?'numbers':order<33?'colors':'family',order,reviewTags:[]}));
const makeExercises=(id:string,words:readonly string[],sentence:string,translation:string)=>[
 {id:`${id}-listen`,type:'audio-word' as const,instruction:'Listen and choose.',prompt:words[0],answer:words[0],options:words.slice(0,3).map(x=>({id:x,label:vocabulary.find(v=>v.id===x)?.french||x,audioText:vocabulary.find(v=>v.id===x)?.french})),audioText:vocabulary.find(v=>v.id===words[0])?.french,ageModes:['early','junior','explorer','adult'] as const},
 {id:`${id}-match`,type:'fr-en' as const,instruction:'Match the meaning.',prompt:vocabulary.find(v=>v.id===words[1])?.french||'',answer:vocabulary.find(v=>v.id===words[1])?.english||'',options:words.slice(0,3).map(x=>({id:x,label:vocabulary.find(v=>v.id===x)?.english||x})),ageModes:['early','junior','explorer','adult'] as const},
 {id:`${id}-picture`,type:'audio-picture' as const,instruction:'Listen and tap the picture.',prompt:words[2],answer:words[2],options:words.slice(0,3).map(x=>({id:x,label:vocabulary.find(v=>v.id===x)?.image||x,image:vocabulary.find(v=>v.id===x)?.image})),audioText:vocabulary.find(v=>v.id===words[2])?.french,ageModes:['early','junior','explorer','adult'] as const},
 {id:`${id}-order`,type:'sentence-order' as const,instruction:'Put the words in order.',prompt:translation,answer:sentence,options:sentence.split(' ').map((x,i)=>({id:String(i),label:x})),ageModes:['junior','explorer','adult'] as const},
 {id:`${id}-missing`,type:'missing-word' as const,instruction:'Complete the sentence.',prompt:sentence.replace(/\S+$/,'___'),answer:sentence.split(' ').at(-1)||'',options:words.slice(0,3).map(x=>({id:x,label:vocabulary.find(v=>v.id===x)?.french||x})),ageModes:['junior','explorer','adult'] as const},
 {id:`${id}-speak`,type:'pronunciation' as const,instruction:'Hear it, then record your voice.',prompt:sentence,answer:sentence,options:[],audioText:sentence,ageModes:['early','junior','explorer','adult'] as const},
 {id:`${id}-dialogue`,type:'dialogue-response' as const,instruction:'Choose the friendly reply.',prompt:sentence,answer:words[0],options:words.slice(0,3).map(x=>({id:x,label:vocabulary.find(v=>v.id===x)?.french||x})),ageModes:['early','junior','explorer','adult'] as const},
 {id:`${id}-review`,type:'review' as const,instruction:'Final check.',prompt:vocabulary.find(v=>v.id===words[0])?.english||'',answer:words[0],options:words.slice(0,3).map(x=>({id:x,label:vocabulary.find(v=>v.id===x)?.french||x})),ageModes:['early','junior','explorer','adult'] as const}
];
const lessonDefs=[
 ['bonjour','Bonjour!','Greet, thank and say goodbye',['bonjour','salut','bonsoir','au-revoir','merci','svp','oui','non'],'Bonjour Milo','Hello Milo'],
 ['introductions','Je m’appelle…','Introduce yourself and ask a name',['je-mappelle','comment-tu','enchante','je-suis'],'Je m’appelle Milo','My name is Milo'],
 ['numbers','Numbers 1–10','Count and say your age',['un','deux','trois','quatre','cinq','six','sept','huit','neuf','dix','age'],'J’ai six ans','I am six years old'],
 ['colors','Colors','Recognize and name common colors',['rouge','bleu','vert','jaune','orange','rose','noir','blanc','marron','violet'],'C’est rouge','It is red'],
 ['family','My Family','Identify close family members',['famille','mere','pere','soeur','frere','parents','qui'],'C’est ma mère','This is my mother']
] as const;
const lessons=lessonDefs.map(([id,title,outcome,words,sentence,translation],index)=>{const exercises=makeExercises(id,words,sentence,translation);return{id,title,subtitle:outcome,outcome,minutes:8+index,color:['#ef6a5b','#7b75c9','#e2a43c','#47a887','#4d86b5'][index],objectives:[outcome],vocabularyIds:[...words],sections:[{id:`${id}-welcome`,title:'Welcome',kind:'welcome' as const,objective:outcome,exerciseIds:[]},{id:`${id}-listen-section`,title:'Listen and explore',kind:'listen' as const,objective:'Hear natural French',exerciseIds:exercises.slice(0,3).map(e=>e.id)},{id:`${id}-practice`,title:'Use the language',kind:'practice' as const,objective:'Recall and build a phrase',exerciseIds:exercises.slice(3,6).map(e=>e.id)},{id:`${id}-dialogue-section`,title:'Mini dialogue',kind:'dialogue' as const,objective:'Respond in context',exerciseIds:[exercises[6].id]},{id:`${id}-review-section`,title:'Review',kind:'review' as const,objective:'Finish and schedule review',exerciseIds:[exercises[7].id]}],exercises,dialogue:[{speaker:'Milo',french:sentence,english:translation,audio:`tts:${id}:dialogue`}],grammarNotes:[{title:'Notice',body:`Practise the useful pattern: ${sentence}`,ageModes:['explorer','adult']}],culturalNotes:[{title:'French in real life',body:'Listen first, then answer with a friendly voice.'}]}});
export const starterCourse:Course=courseSchema.parse({id:'bonjour-bloom-pre-a1',title:'Pre-A1 Starter Path',version:1,levels:[{id:'pre-a1',cefr:'Pre-A1',title:'First French',unitIds:['starter']}],units:[{id:'starter',title:'First steps in French',description:'Five gentle beginner lessons',lessonIds:lessons.map(l=>l.id)}],lessons,vocabulary,audioAssets:vocabulary.map(v=>({id:v.audio,fallbackText:v.french,locale:'fr-FR' as const}))});
